version: "3.3"
services:
  geth:
    build: .
    restart: unless-stopped
    container_name: ethereum
    expose:
      - "8545"
    env_file:
      - .env
    volumes:
      - ./data:/data

  proxy:
    image: nginx:1.22-alpine
    restart: unless-stopped
    container_name: rpcproxy
    ports:
      - "8545:8545"
    links:
      - geth
    volumes:
      - ./njs:/etc/nginx/njs
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - geth

  faucet:
    image: chainflag/eth-faucet:1.1.0
    restart: unless-stopped
    container_name: ethfaucet
    ports:
      - "8080:8080"
    links:
      - geth
    env_file:
      - .env
    command: -wallet.provider http://geth:8545 -wallet.privkey ${BLOCK_SIGNER_PRIVATE_KEY} -faucet.minutes 1
    depends_on:
      - geth

networks:
  default:
