version: "3.3"
services:
  ethereum:
    build: .
    restart: unless-stopped
    container_name: geth_with_proxy
    ports:
      - "8545:8545"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./logs:/var/log/nginx

  faucet:
    image: chainflag/eth-faucet:1.1.0
    restart: unless-stopped
    container_name: eth_faucet
    ports:
      - "8080:8080"
    links:
      - ethereum
    env_file:
      - .env
    command: -wallet.provider http://ethereum:8545 -wallet.privkey ${ALLOC_ADDRESS_PRIVATE_KEY} -faucet.minutes 1
    depends_on:
      - ethereum

networks:
  default:
